vsphere_resource_pool: /LAB/host/attic/Resources/PKS-MGMT # /<Data Center Name>/host/<Cluster Name>
opsman_vm_name: om-pks
opsman_private_ip: 10.16.11.10
opsman_netmask: 255.255.255.0
vsphere_datastore: EQL-THIN01
vsphere_datacenter: LAB
infrastructure_network: PKS-MGMT
infrastructure_gateway: 10.16.21.1
dns: 192.168.100.50,192.168.100.150
ntp: 192.168.1.1
vsphere_vms_folder: /LAB/vm/BOSH/PKS/VMs/
vcenter_hostname: corevcsa1.ragazzilab.com
vcenter_userid: administrator@vsphere.local
opsman_ssh_public_key:
